import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { supabase } from '../lib/supabase.js';

interface BaselineAssessmentBody {
  rangeTestAudioUrl?: string;
  sustainedHoldAudioUrl?: string;
  noteSchedule?: unknown[];
}

interface BaselineAssessmentParams {
  jobId: string;
}

export default async function assessmentsRoutes(app: FastifyInstance) {
  app.post(
    '/baseline',
    async (request: FastifyRequest<{ Body: BaselineAssessmentBody }>, reply: FastifyReply) => {
      // In a real app, auth.uid would come from the JWT via request.user
      const userId = (request.user as { sub?: string })?.sub;
      if (!userId) {
        return reply.code(401).send({ error: 'Unauthorized' });
      }

      // Generate a job ID (we'll use the snapshot_id generated by Supabase if needed, or create our own UUID)
      const jobId = crypto.randomUUID();

      // Create a pending row in user_baseline_snapshot
      const { data, error } = await supabase
        .from('user_baseline_snapshot')
        .insert({
          snapshot_id: jobId,
          user_id: userId,
          audio_processor_job_id: jobId, // Typically this would be the ID returned by the worker queue
          status: 'pending',
          tier: 'singing',
        })
        .select()
        .single();

      if (error) {
        if ((error as { code?: string })?.code === '23505') {
          return reply.code(409).send({ error: 'Baseline assessment already exists' });
        }
        app.log.error(error, 'Failed to insert baseline snapshot');
        return reply.code(500).send({ error: 'Failed to create baseline assessment job' });
      }

      // Normally here we would enqueue the job to the audio-processor worker
      // (e.g. using graphile-worker or similar)
      // This part is deferred.

      return reply.code(201).send({
        jobId: data.snapshot_id,
        status: data.status,
      });
    }
  );

  app.get(
    '/baseline/:jobId',
    async (request: FastifyRequest<{ Params: BaselineAssessmentParams }>, reply: FastifyReply) => {
      const userId = (request.user as { sub?: string })?.sub;
      if (!userId) {
        return reply.code(401).send({ error: 'Unauthorized' });
      }

      const { jobId } = request.params;

      const { data, error } = await supabase
        .from('user_baseline_snapshot')
        .select('*')
        .eq('snapshot_id', jobId)
        .eq('user_id', userId)
        .single();

      if (error || !data) {
        return reply.code(404).send({ error: 'Baseline assessment not found' });
      }

      // Build the response payload
      const response: Record<string, unknown> = {
        jobId: data.snapshot_id,
        status: data.status,
      };

      // Include completed fields if they exist
      if (data.status === 'complete') {
        response.completedAt = data.completed_at;
        response.voiceType = data.voice_type;
        response.recommendedStartingKeyMidi = data.recommended_key_midi;
        response.qualityFlag = data.quality_flag;
        response.result = data.result_json;
      }

      return reply.code(200).send(response);
    }
  );
}
